name: build kernel module

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/build_tests.yml'
      - 'src/kernel_module/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/build_tests.yml'
      - 'src/kernel_module/**'

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies
      run: sudo apt install linux-headers-`uname -r`
    - name: build
      working-directory: ${{github.workspace}}/src/kernel_module
      shell: bash
      run: make
